export default {
    NO: "No.",
    CORNER_NM: "매장명",
    CORNER: "매장",
    STORE_GROUP: "매장그룹",
    SALE_AMT: "매출금액",
    COMP_RATIO: "구성비",
    MONTH_TOTAL_AMT: "당월누계",
    ITEM_NM: "상품명",
    ITEM_CLASS: "상품분류",
    QTY: "수량",
    SALE_QTY: "판매수량",
    SEARCH_DT: "조회일자",
    VENDOR: "거래처",
    SEARCH_COND: "조회기준",
    SEARCH: "조회",
    GI_QTY: "입고",
    GO_QTY: "출고",
    CUR_STOCK_QTY: "현재고",
    TOTAL_STOCK_QTY: "전재고",
    WH_STOCK_QTY: "창고재고",
    SALE: "판매",
    USE_YN: "사용여부",
    ITEM_CD: "상품코드",
    CORNER_ITEM_NM: "매장 취급상품",
    TEST_TOS_CONTENTS: "제1조 (목적) 이 약관은 SR Mobile(이하 &lsquo;회사&rsquo;)이 제공하는 서비스의 이용과 관련하여 회사와 회원과의 권리, 의무 및 책임사항, 기타 필요한 사항을 규정함을 목적으로 합니다.",
    SHOW_EXIST_STOCK_LIST: "재고존재 내역만 출력",
    DATE: "일자",
    ERROR: '오류',
    PRICE: '단가',
    GAUGE: '게이지',
    GAS_TYPE: '유종',
    TANK_NO: '탱크\n번호',
    GAS_AMT: '유량(재고)',
    TYPE: '구분',
    TOTAL_AMT_SHORT: '합계',
    TOTAL_AMT: '전체 합계',
    ENTER_SEARCH_COND_MSG: '검색조건을 입력해 주십시오.',
    NO_RESULT_MSG: '검색결과가 없습니다.',
    CASH: '현금',
    CARD_ETC: '카드 외',
    SALES_ORG: '사업장',
    NET_AMT: '과세매출',
    DUTY_FREE_AMT: '면세매출',
    TOTAL_SALE_AMT: '총매출',
    ID_INPUT_MSG: '아이디를 입력해주세요.',
    PW_INPUT_MSG: '비밀번호가 일치하지 않습니다.',
    ID_PW_SAVE: '아이디/패스워드 저장',
    LOGIN: '로그인',
    NO_ID_MSG: '계정이 없으신가요?',
    SIGN_UP: '회원가입',
    NEXT: '다음',
    DUP_CHECK: '중복체크',
    AVAILABLE_ID: '사용가능',
    RETURN_LOGIN_PAGE: '로그인으로 돌아가기',
    RETURN_TERMS_PAGE: '약관으로 돌아가기',
    SELECT: '선택',
    ALL: '전체',
    CONFIRM: '확인',
    NAME: '이름',
    ID: '아이디',
    PW: '비밀번호',
    VAT: '부가세',
    NO_SALES_ORG_MSG: '사업장을 선택해주세요.',
    OPER_TYPE_REST: '01',
    OPER_TYPE_OIL: '02'
}
